name: Auto Docs

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    - uses: actions/checkout@master
    - run: |
		npm install -g typedoc 
        npx typedoc
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: docs
        github_token: '${{ secrets.TOKEN  }}'
        source_folder: docs
      if: success() && github.event == 'push'