name: Auto Docs

on:
  push:
    branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - run: |
            npm install -g typedoc 
            npx typedoc
        - uses: actions/upload-artifact@v2
          with:
            name: docs
            path: docs
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: docs
        github_token: '${{ secrets.TOKEN  }}'
        source_folder: docs
      if: success() && github.event == 'push'