# Deployment of Kikku on SSH server
name: Deploy release to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to SSH server
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u TrueBabyChaise --password-stdin

      - name: Build docker image
        run: docker build -t ghcr.io/truebabychaise/kikku .

      - name: Push the client image to GitHub Container Registry
        run: docker push ghcr.io/truebabychaise/kikku:latest

  restart:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: VPS deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u TrueBabyChaise --password-stdin
            cd prod.env
            docker compose down
            docker image rm ghcr.io/truebabychaise/kikku:latest
            docker pull ghcr.io/truebabychaise/kikku:latest
            docker compose up -d
